---
kind: pipeline
type: docker
name: lint

steps:
  - name: Lint Dockerfiles
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint Dockerfile
    when:
      status:
        - failure
        - success

  - name: Lint entrypoint scripts
    image: koalaman/shellcheck-alpine
    commands:
      - shellcheck entrypoint.sh
    when:
      status:
        - failure
        - success

trigger:
  event:
    - pull_request
    - push
  ref:
    exclude:
      - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/flox
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
kind: pipeline
type: docker
name: build and publish

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      CUSTOM_TAGS: latest

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/flox
      password:
        from_secret: dockerhub_password
      username:
        from_secret: dockerhub_username

  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      password:
        from_secret: matrix_password
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
    when:
      status:
        - failure
        - success

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint
