---
kind: pipeline
name: build and publish

steps:
  - name: docker
    image: plugins/docker@sha256:cfa62987b34ca106a1418afb821f436d957f10a186c7faa27feda781ae7f81fd
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: mwalbeck/flox
      tags:
        - "latest"

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: test

steps:
  - name: docker
    image: plugins/docker@sha256:cfa62987b34ca106a1418afb821f436d957f10a186c7faa27feda781ae7f81fd
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/flox
      dry_run: true

trigger:
  event:
    - pull_request
