---
kind: pipeline
name: build and publish

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/flox
      tags:
        - "latest"

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/flox
      dry_run: true

trigger:
  event:
    - pull_request
